version: '3.1'

services:
  mailwizz:
    build: ./mailwizz
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./mailwizz/latest:/var/www/html:rw
    environment:
      TZ: 'Europe/Kiev'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mailwizz'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz'
      MYSQL_PASSWORD: 'mailwizz'
    volumes:
      - nginx-pm-db_mysql:/var/lib/mysql

volumes:
  nginx-pm-db_mysql: